# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6fd7e63a8c2e2ed6b5babb512ca21900661300d53e803da85c4279bb068b9a3889e9bb7c3f696d5a95cb4385bd4766886f83831761d684fe31d3d618a98a39c8

test:
  secret_key_base: f5b42f14fc174b66df20cdb47b6a376e83be607e5e49c0e985ccf696a71fdbde350d34b9bac41948bc80efe3089b59164dee0376b670f01e561c480e645acd3b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
